In [ ]:
!pip3 install torch

Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (2.3.0+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch) (2023.6.0)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch)
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch) (2.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch)
  Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 30.3 MB/s eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
Successfully installed nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105

In [ ]:
!pip3 install torchvision

Requirement already satisfied: torchvision in /usr/local/lib/python3.10/dist-packages (0.18.0+cu121)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchvision) (1.25.2)
Requirement already satisfied: torch==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (2.3.0+cu121)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.10/dist-packages (from torchvision) (9.4.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (4.11.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (2023.6.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (12.1.105)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch==2.3.0->torchvision) (2.3.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch==2.3.0->torchvision) (12.5.40)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch==2.3.0->torchvision) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch==2.3.0->torchvision) (1.3.0)

In [ ]:
!pip3 install -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

In [ ]:
import os
os.kill(os.getpid(), 9)

In [ ]:
! pip install transformers[torch] --upgrade
! pip install accelerate --upgrade

Requirement already satisfied: transformers[torch] in /usr/local/lib/python3.10/dist-packages (4.41.1)
Collecting transformers[torch]
  Downloading transformers-4.41.2-py3-none-any.whl (9.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 47.1 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (3.14.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (0.23.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (24.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (2024.5.15)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (0.4.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (4.66.4)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from transformers[torch]) (2.3.0+cu121)
Collecting accelerate>=0.21.0 (from transformers[torch])
  Downloading accelerate-0.30.1-py3-none-any.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.6/302.6 kB 24.4 MB/s eta 0:00:00
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate>=0.21.0->transformers[torch]) (5.9.5)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers[torch]) (2023.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.0->transformers[torch]) (4.12.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch->transformers[torch]) (1.12.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch->transformers[torch]) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch->transformers[torch]) (3.1.4)
Collecting nvidia-cuda-nvrtc-cu12==12.1.105 (from torch->transformers[torch])
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
Collecting nvidia-cuda-runtime-cu12==12.1.105 (from torch->transformers[torch])
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
Collecting nvidia-cuda-cupti-cu12==12.1.105 (from torch->transformers[torch])
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
Collecting nvidia-cudnn-cu12==8.9.2.26 (from torch->transformers[torch])
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
Collecting nvidia-cublas-cu12==12.1.3.1 (from torch->transformers[torch])
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
Collecting nvidia-cufft-cu12==11.0.2.54 (from torch->transformers[torch])
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
Collecting nvidia-curand-cu12==10.3.2.106 (from torch->transformers[torch])
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
Collecting nvidia-cusolver-cu12==11.4.5.107 (from torch->transformers[torch])
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
Collecting nvidia-cusparse-cu12==12.1.0.106 (from torch->transformers[torch])
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
Collecting nvidia-nccl-cu12==2.20.5 (from torch->transformers[torch])
  Using cached nvidia_nccl_cu12-2.20.5-py3-none-manylinux2014_x86_64.whl (176.2 MB)
Collecting nvidia-nvtx-cu12==12.1.105 (from torch->transformers[torch])
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (99 kB)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch->transformers[torch]) (2.3.0)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12==11.4.5.107->torch->transformers[torch])
  Downloading nvidia_nvjitlink_cu12-12.5.40-py3-none-manylinux2014_x86_64.whl (21.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.3/21.3 MB 29.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers[torch]) (2024.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch->transformers[torch]) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch->transformers[torch]) (1.3.0)
Installing collected packages: nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, transformers, accelerate
  Attempting uninstall: transformers
    Found existing installation: transformers 4.41.1
    Uninstalling transformers-4.41.1:
      Successfully uninstalled transformers-4.41.1
Successfully installed accelerate-0.30.1 nvidia-cublas-cu12-12.1.3.1 nvidia-cuda-cupti-cu12-12.1.105 nvidia-cuda-nvrtc-cu12-12.1.105 nvidia-cuda-runtime-cu12-12.1.105 nvidia-cudnn-cu12-8.9.2.26 nvidia-cufft-cu12-11.0.2.54 nvidia-curand-cu12-10.3.2.106 nvidia-cusolver-cu12-11.4.5.107 nvidia-cusparse-cu12-12.1.0.106 nvidia-nccl-cu12-2.20.5 nvidia-nvjitlink-cu12-12.5.40 nvidia-nvtx-cu12-12.1.105 transformers-4.41.2
Requirement already satisfied: accelerate in /usr/local/lib/python3.10/dist-packages (0.30.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (24.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0.1)
Requirement already satisfied: torch>=1.10.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.3.0+cu121)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.23.2)
Requirement already satisfied: safetensors>=0.3.1 in /usr/local/lib/python3.10/dist-packages (from accelerate) (0.4.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.14.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (4.12.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (1.12.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (3.1.4)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2023.6.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: triton==2.3.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.10.0->accelerate) (2.3.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate) (12.5.40)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub->accelerate) (4.66.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub->accelerate) (2024.2.2)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)

In [ ]:
from google.colab import files
uploaded = files.upload()

%mkdir kb-albert-char
%mv config.json pytorch_model.bin tokenizer_config.json vocab.txt ./kb-albert-char

Saving config.json to config.json
Saving LICENSE.txt to LICENSE.txt
Saving pytorch_model.bin to pytorch_model.bin
Saving special_tokens_map.json to special_tokens_map.json
Saving tokenizer_config.json to tokenizer_config.json
Saving vocab.txt to vocab.txt

### 구글 드라이브 연결

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### train data 불러오기

In [ ]:
import pandas as pd

train_df = pd.read_excel('/content/drive/MyDrive/news_train_코사인유사도_전처리 후.xlsx')
test_df = pd.read_excel('/content/drive/MyDrive/news_test_코사인유사도_전처리 후.xlsx')

In [ ]:
train_df

,id,texts,labels,prb,Unnamed: 4,날짜,group_0.5,group_0.6,group_0.7
0,23040404,"한미반도체, 한빛레이저 지분 전량 매각 후 주가 하락세",0,NaN,NaN,2023-04-04,3,3,3
1,23040405,"한미반도체, 하루만에 8% 급락…1만9000원선 무너지나",0,4.0,보합 제거,2023-04-04,4,4,4
2,23040407,[클릭! 이 종목] 한미반도체 8% 급락…계열사가 보유지분 전량 매도,0,NaN,NaN,2023-04-04,6,6,6
3,23040601,한미반도체 주가 '방긋'…1만9480원 2.10% 올라,1,NaN,NaN,2023-04-06,7,7,7
4,23040602,한미반도체 공매도 '160건 이상 감소' 거래량 216→49건... 주가 '함박웃음',1,NaN,NaN,2023-04-06,8,8,8
...,...,...,...,...,...,...,...,...,...
698,24040131,"한미반도체, 듀얼 TC 본더 타이거 출시…매출 증가 기대",1,NaN,NaN,2024-04-01,1157,1239,1316
699,24040135,"한미반도체, ‘DUAL TC BONDER TIGER’ 출시",1,NaN,NaN,2024-04-01,1164,1240,1317
700,24040132,"[증시 종합] SK하닉·한미반도체, 토니모리·코스맥스·아모레·LG생건 등 주가↑",1,NaN,NaN,2024-04-01,1165,1241,1318
701,24040133,계속되는 반도체 상승랠리...삼성전자·SK하이닉스·한미반도체 나란히 신고가 경신,1,NaN,NaN,2024-04-01,1166,1242,1319
702,24040134,"[오늘의 주목주] 'HBM 기대감' 한미반도체 6%대, LS머트리얼즈 10%대 상승",1,NaN,NaN,2024-04-01,1167,1243,1320

In [ ]:
test_df

,id,texts,labels,prb,날짜,group_0.5,group_0.6,group_0.7
0,24041502,"한미반도체, 영업익 1200% 늘었다…목표가↑-상상인",1,NaN,2024-04-15,0,0,0
1,24041503,"한미반도체, HBM 본더 시장 지위 공고…올해 영업익 전망치 38.9% ↑",1,NaN,2024-04-15,1,1,1
2,24041504,"상상인證 “한미반도체, 완벽한 체질 개선의 해…목표가 ↑”",1,NaN,2024-04-15,2,2,2
3,24041505,"상상인증권 ""한미반도체, TC본더 매출 본격화로 체질 개선 전망""",1,NaN,2024-04-15,3,3,3
4,24041511,"상상인證 ""한미반도체 목표가 197% 상향…HBM 본더 시장 지위 공고""",1,NaN,2024-04-15,4,4,4
...,...,...,...,...,...,...,...,...
149,24051402,"한미반도체, 상승 멈추고 2% 낙폭…13만원선 유지",1,NaN,2024-05-14,166,180,196
150,24051404,[N-Stock] 한미반도체 주가 소폭 강세로 좋은 흐름 이어…최근 기관 매수,1,NaN,2024-05-14,168,182,198
151,24051406,"한미반도체, HBM용 TC본더 라인 증설…98.8억 규모 유형자산 취득",1,NaN,2024-05-14,169,183,200
152,24051409,"""HBM 장비 생산력 더 늘린다""…한미반도체, 7번째 공장부지 확보",1,NaN,2024-05-14,171,185,203
153,24051410,"코스피, 눈치보기 속 '소폭 상승'...SK하이닉스 · 한미반도체 '강세'",1,NaN,2024-05-14,172,186,204

In [ ]:
# 텍스트 변환 함수
def replace_symbols(text):
    text = text.replace("↑", "상승")
    text = text.replace("↓", "하락")
    text = text.replace("上", "상승")
    text = text.replace("下", "하락")
    text = text.replace("比", "대비")
    return text

# 텍스트 변환\
train_df['processed_text'] = train_df['texts'].apply(replace_symbols)
test_df['processed_text'] = test_df['texts'].apply(replace_symbols)

##### 리스트 형태로 변환하기 -> 토큰화가 List[str] 형태로만 가능

In [ ]:
X_train = train_df['processed_text'].tolist()
y_train = train_df['labels'].tolist()

X_test = test_df['processed_text'].tolist()
y_test = test_df['labels'].tolist()

### KB-ALBERT 모델 불러오기

In [ ]:
from transformers import AutoModel, AutoTokenizer, AutoModelForSequenceClassification

# Load Tokenizer and Model
pt_model = AutoModel.from_pretrained('/content/drive/MyDrive/kb-albert-char-base-v2')
tokenizer = AutoTokenizer.from_pretrained('/content/drive/MyDrive/kb-albert-char-base-v2')
model = AutoModelForSequenceClassification.from_pretrained("/content/drive/MyDrive/kb-albert-char-base-v2", num_labels=2)

Some weights of AlbertForSequenceClassification were not initialized from the model checkpoint at /content/drive/MyDrive/kb-albert-char-base-v2 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
# 토큰화
train_input = tokenizer(X_train, truncation = True, padding = True,
                        return_tensors="pt")

test_input = tokenizer(X_test, truncation = True, padding = True,
                        return_tensors="pt")

In [ ]:
import torch

class OurDataset(torch.utils.data.Dataset):
  def __init__(self, inputs, labels):
    self.inputs = inputs
    self.labels = labels

  def __getitem__(self, idx):
    item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}
    item['labels'] = torch.tensor(self.labels[idx])
    return item

  def __len__(self):
    return len(self.labels)

In [ ]:
from sklearn.metrics import precision_recall_fscore_support, accuracy_score

def compute_metrics(pred):
    labels = pred.label_ids
    preds = pred.predictions.argmax(-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall
    }

In [ ]:
# Dataset 생성
train_dataset = OurDataset(train_input, y_train)
test_dataset = OurDataset(test_input, y_test)

# 데이터로더 생성
from torch.utils.data import DataLoader

train_loader = DataLoader(train_dataset, shuffle = True, batch_size = 8)
test_loader = DataLoader(test_dataset, batch_size = 16)

In [ ]:
! pip install optuna

Collecting optuna
  Downloading optuna-3.6.1-py3-none-any.whl (380 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 3.1 MB/s eta 0:00:00
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 22.4 MB/s eta 0:00:00
Collecting colorlog (from optuna)
  Downloading colorlog-6.8.2-py3-none-any.whl (11 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from optuna) (1.25.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (24.0)
Requirement already satisfied: sqlalchemy>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from optuna) (2.0.30)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from optuna) (4.66.4)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.10/dist-packages (from optuna) (6.0.1)
Collecting Mako (from alembic>=1.5.0->optuna)
  Downloading Mako-1.3.5-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.6/78.6 kB 10.5 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4 in /usr/local/lib/python3.10/dist-packages (from alembic>=1.5.0->optuna) (4.12.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy>=1.3.0->optuna) (3.0.3)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.10/dist-packages (from Mako->alembic>=1.5.0->optuna) (2.1.5)
Installing collected packages: Mako, colorlog, alembic, optuna
Successfully installed Mako-1.3.5 alembic-1.13.1 colorlog-6.8.2 optuna-3.6.1

In [ ]:
import optuna
from transformers import Trainer
from transformers import TrainingArguments

def objective(trial):
    num_train_epochs = trial.suggest_int('num_train_epochs', 1, 4)
    per_device_train_batch_size = trial.suggest_categorical('per_device_train_batch_size', [8, 16, 32, 64])
    per_device_eval_batch_size = trial.suggest_categorical('per_device_eval_batch_size', [8, 16, 32, 64])
    logging_steps = trial.suggest_categorical('logging_steps', [100, 200, 500])

    training_args = TrainingArguments(
        output_dir='./results',
        num_train_epochs=num_train_epochs,
        per_device_train_batch_size=per_device_train_batch_size,
        per_device_eval_batch_size=per_device_eval_batch_size,
        warmup_steps=500,
        weight_decay=0.01,
        logging_dir='./logs',
        logging_steps=logging_steps
    )

        # Trainer 객체 생성
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics,
    )

    # 모델 훈련 및 평가
    trainer.train()
    eval_result = trainer.evaluate(eval_dataset=test_dataset)
    accuracy = eval_result['eval_accuracy']

    return accuracy

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)

# 최적의 하이퍼파라미터 출력
print("Best trial:")
trial = study.best_trial

print("  Value: ", trial.value)
print("  Params: ")
for key, value in trial.params.items():
    print("    {}: {}".format(key, value))

[I 2024-06-05 08:09:36,723] A new study created in memory with name: no-name-1240ce3b-92cb-47d9-92d5-51deb601a352
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 08:55:30,884] Trial 0 finished with value: 0.7727272727272727 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 8, 'logging_steps': 500}. Best is trial 0 with value: 0.7727272727272727.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 09:07:15,628] Trial 1 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 1, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 32, 'logging_steps': 100}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 09:30:15,660] Trial 2 finished with value: 0.7727272727272727 and parameters: {'num_train_epochs': 2, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 32, 'logging_steps': 100}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 09:41:56,059] Trial 3 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 1, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 8, 'logging_steps': 500}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 10:16:09,391] Trial 4 finished with value: 0.7727272727272727 and parameters: {'num_train_epochs': 3, 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 64, 'logging_steps': 500}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 11:01:18,891] Trial 5 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 16, 'logging_steps': 500}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 11:46:55,612] Trial 6 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 64, 'logging_steps': 200}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 11:58:28,040] Trial 7 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 1, 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 64, 'logging_steps': 500}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 12:42:51,752] Trial 8 finished with value: 0.7792207792207793 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 16, 'per_device_eval_batch_size': 64, 'logging_steps': 200}. Best is trial 1 with value: 0.7792207792207793.
<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

[I 2024-06-05 13:28:02,775] Trial 9 finished with value: 0.7727272727272727 and parameters: {'num_train_epochs': 4, 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'logging_steps': 500}. Best is trial 1 with value: 0.7792207792207793.

Best trial:
  Value:  0.7792207792207793
  Params:
    num_train_epochs: 1
    per_device_train_batch_size: 8
    per_device_eval_batch_size: 32
    logging_steps: 100

In [ ]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs = 1,
    per_device_train_batch_size = 8,
    per_device_eval_batch_size=32,
    warmup_steps = 500,
    weight_decay = 0.01,
    logging_dir='./logs',
    logging_steps = 100,
)

In [ ]:
from transformers import Trainer

trainer = Trainer(
    model= model,
    args=training_args,
    train_dataset = train_dataset,
    eval_dataset =  test_dataset,
    compute_metrics = compute_metrics,
)

trainer.train()

<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

TrainOutput(global_step=88, training_loss=0.0, metrics={'train_runtime': 696.3491, 'train_samples_per_second': 1.01, 'train_steps_per_second': 0.126, 'total_flos': 3084442110360.0, 'train_loss': 0.0, 'epoch': 1.0})

In [ ]:
eval_result = trainer.evaluate(eval_dataset=test_dataset)
print(eval_result)

<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

{'eval_loss': 0.8331721425056458, 'eval_accuracy': 0.5823293172690763, 'eval_f1': 0.7360406091370558, 'eval_precision': 0.5823293172690763, 'eval_recall': 1.0, 'eval_runtime': 56.6412, 'eval_samples_per_second': 4.396, 'eval_steps_per_second': 0.282, 'epoch': 2.0}

In [ ]:
# 평가 데이터셋에 대한 예측 수행
predictions = trainer.predict(test_dataset)
predicted_labels = predictions.predictions.argmax(axis=-1)

# 예측 결과를 데이터프레임에 추가
test_texts = test_df['texts']  # 원본 텍스트 가져오기
results_df = pd.DataFrame({
    'text': test_texts,
    'true_label': test_df['labels'],
    'predicted_label': predicted_labels
})

print(results_df)

<ipython-input-10-e2154dc18c1f>:9: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  item = {key: torch.tensor(val[idx]) for key, val in self.inputs.items()}

                                            text  true_label  predicted_label
0                  한미반도체, 영업익 1200% 늘었다…목표가↑-상상인           1                1
1      한미반도체, HBM 본더 시장 지위 공고…올해 영업익 전망치 38.9% ↑           1                1
2               상상인證 “한미반도체, 완벽한 체질 개선의 해…목표가 ↑”           1                1
3           상상인증권 "한미반도체, TC본더 매출 본격화로 체질 개선 전망"           1                1
4       상상인證 "한미반도체 목표가 197% 상향…HBM 본더 시장 지위 공고"           1                1
..                                           ...         ...              ...
149                 한미반도체, 상승 멈추고 2% 낙폭…13만원선 유지           1                0
150  [N-Stock] 한미반도체 주가 소폭 강세로 좋은 흐름 이어…최근 기관 매수           1                1
151      한미반도체, HBM용 TC본더 라인 증설…98.8억 규모 유형자산 취득           1                1
152        "HBM 장비 생산력 더 늘린다"…한미반도체, 7번째 공장부지 확보           1                1
153    코스피, 눈치보기 속 '소폭 상승'...SK하이닉스 · 한미반도체 '강세'           1                1

[154 rows x 3 columns]

In [ ]:
results_df.to_excel('kb-albert_하이퍼파라미터.xlsx')

# Colab을 통해 엑셀 파일 다운로드
from google.colab import files
files.download("kb-albert_하이퍼파라미터.xlsx")

In [ ]:
from sklearn.metrics import classification_report

print(classification_report(test_df['labels'], predicted_labels))

              precision    recall  f1-score   support

           0       0.70      0.18      0.29        39
           1       0.78      0.97      0.86       115

    accuracy                           0.77       154
   macro avg       0.74      0.58      0.58       154
weighted avg       0.76      0.77      0.72       154